networks:
    default:
        name: somnium_network
x-service: &service
    volumes:
        - type: bind
          source: .
          target: /var/www
    restart: unless-stopped
services:
    nginx:
        <<: *service
        container_name: somnium_nginx
        image: ghcr.io/somnium-php/somnium/nginx:r1.0-dev
        depends_on:
            - php
    php:
        <<: *service
        container_name: somnium_php
        image: ghcr.io/somnium-php/somnium/php:8.3-r1.0-dev
        environment:
            PHP_IDE_CONFIG: "serverName=somnium"
