name: 'Docker Publish: PHP'

on:
    push:
        branches:
            - main
        paths:
            - docker/php/**
    workflow_dispatch:

jobs:
    docker-publish:
        uses: ./.github/workflows/docker-publish.yml
        with:
            registry-namespace: ${{ github.repository }}
            context: docker/php
            targets: |
                [
                    "{'target':'release', 'tag':'php:8.3-r1.0'}",
                    "{'target':'develop', 'tag':'php:8.3-r1.0-dev'}"
                ]
            build-args: |
                UBUNTU_VERSION=22.04
                PHP_VERSION=8.3
        secrets:
            registry-username: ${{ github.actor }}
            registry-password: ${{ secrets.GITHUB_TOKEN }}
