name: 'Docker Publish'

on:
    workflow_call:
        inputs:
            registry-domain:
                type: string
                description: 'The container registry domain'
                required: false
                default: ghcr.io
            registry-namespace:
                type: string
                description: 'The container registry namespace'
                required: true
            context:
                type: string
                description: 'The path to the Dockerfile'
                required: true
            targets:
                type: string
                description: 'The target Dockerfile layers and tags (JSON)'
                required: true
            platforms:
                type: string
                description: 'The platforms to include in the container image'
                required: false
                default: linux/amd64,linux/arm64
            build-args:
                type: string
                description: 'Any build args to pass to the Docker builder'
                required: false
        secrets:
            registry-username:
                description: 'The container registry username'
                required: true
            registry-password:
                description: 'The container registry password'
                required: true

jobs:
    docker-publish:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                target: ${{ fromJSON(inputs.targets) }}
            max-parallel: 1
        steps:
            - name: 'Check out the repository'
              uses: actions/checkout@v4
            - name: 'Set up QEMU'
              uses: docker/setup-qemu-action@v3
            - name: 'Set up Docker Buildx'
              uses: docker/setup-buildx-action@v3
            - name: 'Log into the container registry'
              uses: docker/login-action@v3
              with:
                  registry: ${{ inputs.registry-domain }}
                  username: ${{ secrets.registry-username }}
                  password: ${{ secrets.registry-password }}
            - name: 'Publish container image'
              uses: docker/build-push-action@v5
              with:
                  context: ${{ inputs.context }}
                  target: ${{ fromJSON(matrix.target).target }}
                  platforms: ${{ inputs.platforms }}
                  build-args: ${{ inputs.build-args }}
                  tags: ${{ inputs.registry-domain }}/${{ inputs.registry-namespace }}/${{ fromJSON(matrix.target).tag }}
                  push: true
                  cache-from: type=gha,scope=${{ github.workflow }}
                  cache-to: type=gha,mode=max,scope=${{ github.workflow }}
