name: 'Docker Publish: Nginx'

on:
    push:
        branches:
            - main
        paths:
            - docker/nginx/**
    workflow_dispatch:

jobs:
    docker-publish:
        uses: ./.github/workflows/docker-publish.yml
        with:
            registry-namespace: ${{ github.repository }}
            context: docker/nginx
            targets: |
                [
                    "{'target':'release', 'tag':'nginx:r1.0'}",
                    "{'target':'develop', 'tag':'nginx:r1.0-dev'}"
                ]
            build-args: UBUNTU_VERSION=22.04
        secrets:
            registry-username: ${{ github.actor }}
            registry-password: ${{ secrets.GITHUB_TOKEN }}
